### PR TITLE
Swipe to throw

### PR DESCRIPTION
**Pull request by jesperlundqvist**

### CODE REVIEW

**Comment by Lunkers** [comment]
@bonnes1 @matlar4 could you check if this works on android as well? We've only been able to test on iOS.

**Review by Lunkers — APPROVED** [review]
This looks good to me. I think we can merge it.

**Review by bonnes1 — APPROVED** [review]
Seems to work on android as well, with the standard settings we use! Great work 💯

**Comment by Lunkers** [comment]
@jesperlundqvist merge whenever

**Pull request merged**
